config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  VALID_STATUSES = ['chinese', 'italian', 'japanese', 'french', 'belgian']

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: VALID_STATUSES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { greater_than: -1, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end;

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end


  # This is only necessary if we have the "add new" form on a separate page
  # This is all the XXX.new is doing
  # A better way to do this is to have the form in the show page
  # If this is done then there is no need to define new in the controller
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>
<hr>
<br>

<% @restaurants.each do |restaurant| %>
  <p>Restaurant Name: <%= link_to restaurant.name, restaurant_path(restaurant) %></p>
  <p>Address: <%= restaurant.address %></p>
  <p>Phone number: <%= restaurant.phone_number %></p>
  <p>Cuisine: <%= restaurant.category.capitalize %></p>
  <br>
<% end %>

<p><%= link_to "Add a new restaurant", new_restaurant_path %></p>

app/views/restaurants/show.html.erb
<h1>Restaurants Details</h1>
<hr>
<br>

<p>Name: <%= @restaurant.name %> (ID: <%= @restaurant.id %>)</p>
<p>Address: <%= @restaurant.address %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>
<p>Cuisine: <%= @restaurant.category.capitalize %></p>
<p>Reviews: <% @restaurant.reviews.each do |review| %></p>
  <p> - <%= review.content %> | Rating: <%= review.rating %></p>
<% end %>
<br>

<%= link_to "Back to Restaurants |", restaurants_path %>
<%= link_to "Edit restaurant |", edit_restaurant_path(@restaurant) %>
<%= link_to "Add a review |", new_restaurant_review_path(@restaurant) %>
<%= link_to restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="fa fa-trash" aria-hidden="true"></i>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>